### ISSUE TITLE
Discussion: How to aggregate time spent in different sleep states?

### ISSUE THREAD

**Issue by Intecpsp** [ryanbdclark/owlet#6]
Since 'Sleep state' is a sensor with text data states, how would I aggregate the time spent in every state to satisfy new sensors for length of entire sleep, length of light sleep, length of deep sleep, length of awake?

**Comment by Intecpsp** [comment]
Right now I kinda have it jerry rigged together with these [History Stats](https://www.home-assistant.io/integrations/history_stats/) configs:

```
- platform: history_stats
  name: "Oakley in 'Light sleep'"
  entity_id: sensor.owlet_baby_care_sock_sleep_state
  state: "light_sleep"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 4
- platform: history_stats
  name: "Oakley in 'Deep sleep'"
  entity_id: sensor.owlet_baby_care_sock_sleep_state
  state: "deep_sleep"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 4
- platform: history_stats
  name: "Oakley in 'Awake'"
  entity_id: sensor.owlet_baby_care_sock_sleep_state
  state: "awake"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 4
```

Then these template helpers

(length actually asleep)
`{{ states('sensor.oakley_in_light_sleep') | float + states('sensor.oakley_in_deep_sleep') | float }}`

(length since starting "sleep time")
`{{ states('sensor.oakley_in_light_sleep') | float + states('sensor.oakley_in_deep_sleep') | float + states('sensor.oakley_in_awake') | float }}`

My issue here is that this is set to a static 4 hours, so will only work for naps. I'd like to find a way to grab the last time it went from `unknown` to something else and use that as the starting point.

Is this a feature that this integration could provide as new sensors?
